# Spring Cloud Config Server Configuration
server.port=8888
spring.application.name=config-server
spring.profiles.active=git

# Native Backend (Local classpath)
spring.cloud.config.server.native.search-locations=classpath:/config

# Git Backend Profile (Active when --spring.profiles.active=git)
spring.cloud.config.server.git.uri=https://github.com/kavimalarsakthivel/Configuration.git
spring.cloud.config.server.git.search-paths=RailwayConfiguration
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.timeout=5

# Eureka Client
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Actuator & Monitoring
management.endpoints.web.exposure.include=health,info
